version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/code                # ローカルコードをコンテナにマウント
    working_dir: /code         # 作業ディレクトリを /code に設定
    command: >
      sh -c "PYTHONPATH=. pytest -q --cov=app --cov-report=term-missing"
